In [ ]:
import os
from dotenv import load_dotenv
import redcap
import pandas as pd

# Load environment variables
load_dotenv()

# Initialize REDCap projects
df = redcap.Project(
    os.getenv('REDCAP_MAIN_URL'),
    os.getenv('REDCAP_MAIN_TOKEN')
)

ck_wk = redcap.Project(
    os.getenv('REDCAP_CK_WK_URL'),
    os.getenv('REDCAP_CK_WK_TOKEN')
)

indigo = redcap.Project(
    os.getenv('REDCAP_INDIGO_URL'),
    os.getenv('REDCAP_INDIGO_TOKEN')
)

In [2]:
df_enumeration_and_sensitisation=ck_wk.export_records(forms=['enumeration_and_sensitisation'])
df_enumeration_and_sensitisation=pd.DataFrame(df_enumeration_and_sensitisation)
village_mapping = {
'001':	'DUMBUTO',
'002':	'SANKANDI',
'003':	'JATTABA',
'005':	'JIFFARONG',
'006':	'BAJANA',
'007':	'KULI KUNDA',
'008':	'JAMARU',
'009':	'BRIKAMANDING',
'010':	'KANTONG KUNDA',
'011':	'JALI',
'013':	'MANDUAR',
'014':	'BANG KULING',
'015':	'GISSAY',
'016':	'TANKULAR',
'017':	'JOLI',
'018':	'KUYANG',
'019':	'BANTASU',
'020':	'SANTAMBA',
'021':	'MISSIRA',
'022':	'TABORANGKOTO',
'023':	'BURONG',
'024':	'JULA KUNDA',
'025':	'KARANTABA',
'026':	'MANDINA',
'027':	'JANNEH KUNDA',
'028':	'KEMOTO',
'029':	'KENEBA',
'030':	'BATELLING',
'031':	'SANDENG',
'032':	'WUDEBA',
'034':	'KENOKOTO',
'035':	'MANARI',
'036':	'NINETEEN',
'040':	'WUROKANG',
'041':	'KWINELLA SANSANKONO',
'042':	'KWINELLA NIA KUNDA',
'043':	'TENDABA',
'044':	'BUMARR',
'045':	'BAMBAKO',
'046':	'KUNDONG MARIAYA',
'047':	'NEMA',
'048':	'KUNDANG NUMU KUNDA',
'049':	'KUNDANG FULA KUNDA',
'050':	'NEMA KUTA',
'051':	'JIRROFF',
'052':	'MADINA ANGALLEH',
'053':	'JATTA KUNDA',
'054':	'MANDINA CENTRAL',
'055':	'SARE SARJO',
'056':	'SIBETO',
'057':	'SARE NDALLA',
'058':	'TABANANI',
'060':	'WILLINGARA',
'061':	'SARE MAMUDU',
'070':	'KOLIOR',
'071':	'JOMARR',
'072':	'JASOBO',
'073':	'SARE MUSA',
'074':	'YORRO JULA',
'075':	'BABOU YAA',
'076':	'MASEMBEH',
'077':	'GENIERE',
'078':	'KAIAF',
'079':	'MADINA KAIAF',
'080':	'SARE SAMBA',
'081':	'MADINA CEESAY KUNDA',
'082':	'NJOLFEN',
'083':	'TORANKA BANTANG',
'084':	'SAREH PATEH',
'085':	'MUNKUTALA',
    # Add more mappings as needed
}

# Assuming sen_log_data is your DataFrame
df_enumeration_and_sensitisation['enu_village'] = df_enumeration_and_sensitisation['enu_village'].map(village_mapping)

In [3]:
df_enumeration_and_sensitisation=df_enumeration_and_sensitisation[['wk_ckno','compoundno',
       'redcap_repeat_instance', 'enu_village', 'enu_comp',
       'enu_date', 'enu_name', 'enu_dob', 'enu_mname', 'enu_fname',
       'enu_age', 'enu_dob_estimated', 'enu_dobsource', 'enu_sensitisation',
       'sen_date', 'sen_visitstatus', 'sen_comment', 'sen_ppregnant',
       'sen_explained', 'sen_icd_given', 'sen_contact1', 'sen_contact2',
       'sen_contact3', 'sen_contact4','sen_outcome','sen_staffid',
       'enumeration_and_sensitisation_complete']]

Eden consent

In [6]:
#consent
df_screen=df.export_records(forms=['consent'])
df_screen=pd.DataFrame(df_screen)
df_screen=df_screen[
    (df_screen['cconsent']=='0')|
    (df_screen['cconsent']=='1')
]
df_screen=df_screen[['participant_id','ck_wkno','consent_form_date_q10','cconsent']]
df_screen= df_screen.sort_values(by=['participant_id','consent_form_date_q10'])
df_screen= df_screen.drop_duplicates(subset='participant_id', keep='last')

df_consent_v4=df_screen[
    (df_screen['consent_form_date_q10']>='2023-12-19')
]
df_consented_v4=df_consent_v4[
    (df_consent_v4['cconsent']=='1')
]

df_decline_consent_v4=df_consent_v4[
    (df_consent_v4['cconsent']=='0')
]

HCG positives

In [8]:
# HCG positives 
df_HCG_positive=df.export_records(forms=['pregnancy_test_result'])
df_HCG_positive=pd.DataFrame(df_HCG_positive)
df_HCG_positive=df_HCG_positive[
    (df_HCG_positive['pt_pregnancy_positive_q3']=='1')
]
df_HCG_positive_wit_duplicate=df_HCG_positive[['participant_id','prg_cycle','pt_testdate_q1','pt_pregnancy_positive_q3']]
df_HCG_positive_wit_duplicate.to_csv('df_HCG_positive_wit_duplicate,csv',index=False)
df_HCG_positive=df_HCG_positive[['participant_id','prg_cycle','pt_testdate_q1','pt_pregnancy_positive_q3']]
df_HCG_positive= df_HCG_positive.sort_values(by=['participant_id','pt_testdate_q1'])
df_HCG_positive = df_HCG_positive.drop_duplicates(subset='participant_id', keep='last')

Sample collection

In [9]:
#Sample 
df_sample_collection=df.export_records(forms=['preganancy_stool_collection', 'maternal_blood_sample_collection',
'preganancy_urine_collection'])
df_sample_collection=pd.DataFrame(df_sample_collection)

confirm scann

In [40]:
#eden confirm Scan by aultrasound 
df_eden_scan=df.export_records(forms=['ultrasound_scan'])
df_eden_scan=pd.DataFrame(df_eden_scan)
df_booking=df_eden_scan[
    (df_eden_scan['pregnancy_confirmed_by_ult']=='1')  
]
#booking 

df_eden_booking=df_booking[
    (df_eden_scan['uss_week']=='1')
].drop_duplicates('participant_id')

df_eden_booking=df_eden_booking[['participant_id','conception_date','comments_scan']]

#week 20
df_eden_week_20=df_booking[
    (df_eden_scan['uss_week']=='2')
].drop_duplicates('participant_id')

df_eden_week_20=df_eden_week_20[['participant_id','ultrascan_date','conception_date', 'ultrascan_ga',
       'ultrascan_ga_days','comments_scan']]
#week 28
df_eden_week_28=df_booking[
    (df_eden_scan['uss_week']=='3')
].drop_duplicates('participant_id')

df_eden_week_28=df_eden_week_28[['participant_id']]
#week 36
df_eden_week_36=df_booking[
    (df_eden_scan['uss_week']=='4')
].drop_duplicates('participant_id')
df_eden_week_36=df_eden_week_36[['participant_id']]

C:\Users\abliebah\AppData\Local\Temp\ipykernel_21144\3353901230.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_eden_booking=df_booking[
C:\Users\abliebah\AppData\Local\Temp\ipykernel_21144\3353901230.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_eden_week_20=df_booking[
C:\Users\abliebah\AppData\Local\Temp\ipykernel_21144\3353901230.py:23: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_eden_week_28=df_booking[
C:\Users\abliebah\AppData\Local\Temp\ipykernel_21144\3353901230.py:29: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_eden_week_36=df_booking[

In [11]:
# withdrawal 
df_withdrawal=df.export_records(forms=['withdrawal'])
df_withdrawal=pd.DataFrame(df_withdrawal)
df_withdrawal = df_withdrawal[
    (df_withdrawal['wd_vdadte_q1']!= '')
]
df_withdrawal = df_withdrawal[['participant_id', 'wd_reason_q5___1', 'wd_reason_q5___2',
       'wd_reason_q5___3', 'wd_reason_q5___4', 'wd_reason_q5___5',
       'wd_reason_q5___6', 'b_give_medical_reason',]]
withdaw_map={
    '1':'Moved away',
    '2':'Parent/Guardian withdrew consent',
    '3':'Due to Medical reasons',
    '4':'Died',
    '5':'Other',
    '6':'No reason given',
}
df_withdrawal['wd_reason_q5___1'] = df_withdrawal['wd_reason_q5___1'].map(withdaw_map)
df_withdrawal['wd_reason_q5___2'] = df_withdrawal['wd_reason_q5___2'].map(withdaw_map)
df_withdrawal['wd_reason_q5___3'] = df_withdrawal['wd_reason_q5___3'].map(withdaw_map)
df_withdrawal['wd_reason_q5___4'] = df_withdrawal['wd_reason_q5___4'].map(withdaw_map)
df_withdrawal['wd_reason_q5___5'] = df_withdrawal['wd_reason_q5___5'].map(withdaw_map)
df_withdrawal['wd_reason_q5___6'] = df_withdrawal['wd_reason_q5___6'].map(withdaw_map)

# Columns to combine into one column
cols_to_combine = ['wd_reason_q5___1', 'wd_reason_q5___2', 'wd_reason_q5___3',
                   'wd_reason_q5___4', 'wd_reason_q5___5', 'wd_reason_q5___6']

# Combine the specified columns into a single 'reason' column
df_withdrawal['combined_reason'] = df_withdrawal[cols_to_combine].apply(
    lambda row: ' '.join(sorted([str(val) for val in row if pd.notna(val) and val != 'nan'])), axis=1
)

# Select the final set of columns, including the new 'combined_reason' column
df_withdrawal = df_withdrawal[['participant_id','combined_reason', 'b_give_medical_reason']]

#df_withdrawal.to_csv('df_withdrawal.csv',index=False)

In [12]:
df_lmp=df.export_records(forms=['lmp'])
df_lmp=pd.DataFrame(df_lmp)

In [13]:
df_lmp_start='2024-11-20'
df_lmp=df_lmp[
    (df_lmp['lmp_form_date_q5']>=df_lmp_start)
]
df_lmp = df_lmp.sort_values(by=['participant_id', 'lmp_form_date_q5'])
df_lmp=df_lmp.drop_duplicates('participant_id')

eden indigo deliveries

In [14]:
#eden deveries 
df_eden_deliveries=df.export_records(forms=['delivery'])
df_eden_deliveries=pd.DataFrame(df_eden_deliveries)
df_eden_deliveries=df_eden_deliveries[
    (df_eden_deliveries['del_ddate_q7']!='')&
    (df_eden_deliveries['del_outcome_q9']=='1')
    
]
df_eden_deliveries=df_eden_deliveries[['participant_id','del_ddate_q7','del_sex_q10','delivery_complete']]

In [15]:
#export indigo scann
df_indigo_ultrasound_scann=indigo.export_records(forms=['ultrasound_scan'])
df_indigo_ultrasound_scann=pd.DataFrame(df_indigo_ultrasound_scann)

In [17]:
#indigo _scann
df_indigo_scann=indigo.export_records(forms=['consent','ultrasound_scan'])
df_indigo_scann=pd.DataFrame(df_indigo_scann)
df_indigo_scann = df_indigo_scann[
    (df_indigo_scann['con_eden_participant_q10']=='1')&
    (df_indigo_scann['pregnancy_confirmed_by_ult_q2'])
]
#eden indigo numbers 
df_eden_indigo_id=df_indigo_scann[['con_participantid_q1','con_participant_eden_num_q11','ultsc_date','ga_weeks', 'ga_days','comments_scan']]

#export indigo scann
df_indigo_ultrasound_scann=indigo.export_records(forms=['ultrasound_scan'])
df_indigo_ultrasound_scann=pd.DataFrame(df_indigo_ultrasound_scann)

#week_20
df_indigo_week_20=df_indigo_ultrasound_scann[
    (df_indigo_ultrasound_scann['redcap_event_name']=='week_20_arm_1')&
    (df_indigo_ultrasound_scann['pregnancy_confirmed_by_ult_q2']=='1')
]

#week 28 
df_indigo_week_28=df_indigo_ultrasound_scann[
    (df_indigo_ultrasound_scann['redcap_event_name']=='week_28_arm_1')&
    (df_indigo_ultrasound_scann['pregnancy_confirmed_by_ult_q2']=='1')
]

#week 36
df_indigo_week_36=df_indigo_ultrasound_scann[
    (df_indigo_ultrasound_scann['redcap_event_name']=='week_36_arm_1')&
    (df_indigo_ultrasound_scann['pregnancy_confirmed_by_ult_q2']=='1')
]

# To match df_indigo_week_20,df_eden_indigo_id the indigo participant_id
df_merged_week_20=pd.merge(df_indigo_week_20,df_eden_indigo_id,on='con_participantid_q1', how='inner')
df_merged_week_28=pd.merge(df_indigo_week_28,df_eden_indigo_id,on='con_participantid_q1', how='inner')
df_merged_week_36=pd.merge(df_indigo_week_36,df_eden_indigo_id,on='con_participantid_q1', how='inner')

df_eden_indigo_id=df_eden_indigo_id.rename(columns={'con_participant_eden_num_q11':'participant_id'})
df_merged_week_20=df_merged_week_20[['con_participantid_q1', 'con_participant_eden_num_q11']]
df_merged_week_20=df_merged_week_20.rename(columns={'con_participant_eden_num_q11':'participant_id'})
df_merged_week_28=df_merged_week_28[['con_participantid_q1', 'con_participant_eden_num_q11']]
df_merged_week_28=df_merged_week_28.rename(columns={'con_participant_eden_num_q11':'participant_id'})
df_merged_week_36=df_merged_week_36[['con_participantid_q1', 'con_participant_eden_num_q11']]
df_merged_week_36=df_merged_week_36.rename(columns={'con_participant_eden_num_q11':'participant_id'})

#eden indigo booking 
df_eden_indigo_booking=pd.concat([df_eden_booking,df_eden_indigo_id],ignore_index= True)
df_eden_indigo_booking=df_eden_indigo_booking.drop_duplicates('participant_id')


#eden indigo week 20
df_eden_indigo_week_20=pd.concat([df_eden_week_20,df_merged_week_20],ignore_index= True)
df_eden_indigo_week_20=df_eden_indigo_week_20.drop_duplicates('participant_id')

# eden indigo week 28 
df_eden_indigo_week_28=pd.concat([df_eden_week_28,df_merged_week_28],ignore_index= True)
df_eden_indigo_week_28=df_eden_indigo_week_28.drop_duplicates('participant_id')


# eden indigo week 36
df_eden_indigo_week_36=pd.concat([df_eden_week_36,df_merged_week_36],ignore_index= True)
df_eden_indigo_week_36=df_eden_indigo_week_36.drop_duplicates('participant_id')

In [18]:
df_indigo_deliveries=indigo.export_records(forms=['delivery'])
df_indigo_deliveries=pd.DataFrame(df_indigo_deliveries)

df_indigo_deliveries=df_indigo_deliveries[
    (df_indigo_deliveries['del_ddate_q7']!='')
]
df_indigo_deliveries=df_indigo_deliveries[['con_participantid_q1', 'del_ddate_q7', 'del_sex_q10','del_outcome_q9']]
df_indigo_deliveries=pd.merge(df_eden_indigo_id,df_indigo_deliveries,on='con_participantid_q1',how='inner')

df_indigo_deliveries=df_indigo_deliveries.rename(columns={'con_participant_eden_num_q11':'participant_id'})

In [19]:
df_eden_collect=df.export_records(forms=['cordcollection'])
df_eden_collect=pd.DataFrame(df_eden_collect)
df_eden_collect=df_eden_collect[
    (df_eden_collect['cordcollection_complete']=='1')|
    (df_eden_collect['cordcollection_complete']=='2')

]
# eden cord collection
df_eden_cord_collection=df_eden_collect[
    (df_eden_collect['cod_vailable']=='1')
]
df_eden_cord_collection=df_eden_cord_collection[['participant_id','cordcollection_form_date_q15','cod_vailable']]
#eden placenta collection
df_eden_placenta_collection=df_eden_collect[
    (df_eden_collect['placenta_available']=='1')
]
df_eden_no_placenta_collection=df_eden_collect[
    (df_eden_collect['placenta_available']=='0')
]
df_eden_placenta_collection=df_eden_placenta_collection[['participant_id','cordcollection_form_date_q15','placenta_available']]
R=pd.merge(df_eden_placenta_collection,df_eden_booking,on='participant_id',how='left')
R.to_csv('placenta_conception.csv',index=False)

In [20]:
df_indigo_collection=indigo.export_records(forms=['cord_blood_collection'])
df_indigo_collection=pd.DataFrame(df_indigo_collection)

df_indigo_collection=df_indigo_collection[
(df_indigo_collection['cord_blood_collection_complete']=='1')|
(df_indigo_collection['cord_blood_collection_complete']=='2')
]

df_indigo_collection=pd.merge(df_indigo_collection,df_eden_indigo_id,on='con_participantid_q1',how='inner')
#indigo cord collection 
df_indigo_cord_collection=df_indigo_collection[
(df_indigo_collection['cbc_cord_blood_q3']=='1')
]
df_indigo_cord_collection=df_indigo_cord_collection[['con_participantid_q1','participant_id','date_form_completed_15','cbc_cord_blood_q3']]

#indigo placenta collection 
df_indigo_placenta_collection=df_indigo_collection[
(df_indigo_collection['placenta_available']=='1')
]
df_indigo_placenta_collection=df_indigo_placenta_collection[['con_participantid_q1','participant_id','date_form_completed_15','placenta_available']]

seasonal blood

In [22]:
# seasonal blood collection 
df_seasonal_blood_collection=df.export_records(forms=['seasonal_blood_collection_2'])
df_seasonal_blood_collection=pd.DataFrame(df_seasonal_blood_collection)
df_seasonal_blood_collection_=df_seasonal_blood_collection[['participant_id','sbc_date','sbc_available','sbc_season']]

In [23]:
data_lmp=df.export_records(forms=['lmp'])
data_lmp=pd.DataFrame(data_lmp)
data_lmp=data_lmp[
    (data_lmp['lmp_complete']=='2')
]
data_lmp=data_lmp[['participant_id','lmp_cycle','lmp_form_date_q5','lmp_temp_exclude___1','lmp_temp_exclude___2','lmp_temp_exclude___3','lmp_temp_exclude___4','lmp_temp_exclude_oth','lmp_complete']]
data_lmp_last_visit=data_lmp[['participant_id','lmp_form_date_q5','lmp_temp_exclude___1','lmp_temp_exclude___2','lmp_temp_exclude___3','lmp_temp_exclude___4','lmp_temp_exclude_oth']]
data_lmp_last_visit = data_lmp_last_visit.sort_values(by=['participant_id', 'lmp_form_date_q5'])
data_lmp_last_visit=data_lmp_last_visit.rename(columns={'lmp_cycle':'last LMP cycle Visit'})
data_lmp_last_visit= data_lmp_last_visit.drop_duplicates(subset='participant_id', keep='last')

data_lmp_temp_exclusion=data_lmp_last_visit[['participant_id','lmp_form_date_q5','lmp_temp_exclude___1','lmp_temp_exclude___2','lmp_temp_exclude___3','lmp_temp_exclude___4','lmp_temp_exclude_oth']]
data_lmp_temp_exclusion=data_lmp_temp_exclusion[
    (data_lmp_temp_exclusion['lmp_temp_exclude___1']=='1')|
    (data_lmp_temp_exclusion['lmp_temp_exclude___2']=='1')|
    (data_lmp_temp_exclusion['lmp_temp_exclude___3']=='1')|
    (data_lmp_temp_exclusion['lmp_temp_exclude___4']=='1')
]
lmp_temp_exclude___1 = {
'1':'Single and not intending to get pregnant'}
data_lmp_temp_exclusion['lmp_temp_exclude___1'] = data_lmp_temp_exclusion['lmp_temp_exclude___1'].map(lmp_temp_exclude___1)

lmp_temp_exclude___2 = {
'1':'Husband away and not expected back soon'}
data_lmp_temp_exclusion['lmp_temp_exclude___2'] = data_lmp_temp_exclusion['lmp_temp_exclude___2'].map(lmp_temp_exclude___2)

lmp_temp_exclude___3 = {
'1':'With a child under 12 months'}
data_lmp_temp_exclusion['lmp_temp_exclude___3'] = data_lmp_temp_exclusion['lmp_temp_exclude___3'].map(lmp_temp_exclude___3)

lmp_temp_exclude___4 = {
'1':'Other'}
data_lmp_temp_exclusion['lmp_temp_exclude___4'] = data_lmp_temp_exclusion['lmp_temp_exclude___4'].map(lmp_temp_exclude___4)
data_lmp_temp_exclusion= data_lmp_temp_exclusion.drop_duplicates('participant_id')

In [24]:
# Sensitized
df_enumeration_and_sensitisation = df_enumeration_and_sensitisation[
    (df_enumeration_and_sensitisation['enu_sensitisation'] == '1')
]
df_enumeration_and_sensitisation = df_enumeration_and_sensitisation.sort_values(by=['enu_village', 'enu_name', 'enu_dob', 'enu_mname', 'enu_fname'])

# Interested
df_interested = df_enumeration_and_sensitisation[
    (df_enumeration_and_sensitisation['sen_outcome'] == '1')
]

# Not interested
df_not_interested = df_enumeration_and_sensitisation[
    (df_enumeration_and_sensitisation['sen_outcome'] == '2')
]

# Undecided
df_undecided = df_enumeration_and_sensitisation[
    (df_enumeration_and_sensitisation['sen_outcome'] == '3')
]

# Others
df_other = df_enumeration_and_sensitisation[
    (df_enumeration_and_sensitisation['sen_outcome'] == '')
]


# HCG positive
df_HCG_positive = df_HCG_positive.sort_values(by=['participant_id', 'pt_testdate_q1'])
df_HCG_positive = df_HCG_positive.drop_duplicates(subset='participant_id', keep='last')
#df_HCG_positive=df_HCG_positive[~df_HCG_positive['participant_id'].isin(df_withdrawal['participant_id'])]
# Eden Indigo booking
df_eden_indigo_booking = pd.concat([df_eden_booking, df_eden_indigo_id], ignore_index=True)
df_eden_indigo_booking = df_eden_indigo_booking.drop_duplicates('participant_id')

fellow_up_booking_scan_fellow_up=df_eden_indigo_booking[~df_eden_indigo_booking['participant_id'].isin(df_withdrawal['participant_id'])]
fellow_up_booking_scan_fellow_up1=fellow_up_booking_scan_fellow_up[~fellow_up_booking_scan_fellow_up['participant_id'].isin(df_decline_consent_v4['participant_id'])]
fellow_up_booking_scan_fellow_up1['Are Elegible']='Accept consent'
#fellow_up_booking_scan=fellow_up_booking_scan[~fellow_up_booking_scan['participant_id'].isin(df_eden_indigo_deveries['participant_id'])]
fellow_up_booking_scan=fellow_up_booking_scan_fellow_up.drop_duplicates('participant_id')
fellow_up_booking_scan_fellow_up1=fellow_up_booking_scan_fellow_up1.drop_duplicates('participant_id')

Reason_fellow_up_booking_scan=df_withdrawal[df_withdrawal['participant_id'].isin(df_eden_indigo_booking ['participant_id'])]
Reason_fellow_up_booking_scan.to_csv('Reason_fellow_up_booking_scan.csv',index=False)

Moved_away_Reason_fellow_up_booking_scan=Reason_fellow_up_booking_scan[
    (Reason_fellow_up_booking_scan['combined_reason']!='')
]
no_Reason_Reason_fellow_up_booking_scan=Reason_fellow_up_booking_scan[
    (Reason_fellow_up_booking_scan['combined_reason']=='')
]

# Eden Indigo week 20
df_eden_indigo_week_20 = pd.concat([df_eden_week_20, df_merged_week_20], ignore_index=True)
df_eden_indigo_week_20 = df_eden_indigo_week_20.drop_duplicates('participant_id')

Reason_df_eden_indigo_week_20=df_withdrawal[df_withdrawal['participant_id'].isin(df_eden_indigo_week_20['participant_id'])]
#Reason_df_eden_indigo_week_20=Reason_fellow_up_booking_scan[~Reason_fellow_up_booking_scan['participant_id'].isin(Reason_df_eden_indigo_week_20['participant_id'])]
Reason_df_eden_indigo_week_20.to_csv('Reason_df_eden_indigo_week_20.csv',index=False)

Moved_away_Reason_df_eden_indigo_week_20=Reason_df_eden_indigo_week_20[
    (Reason_df_eden_indigo_week_20['combined_reason']!='')
]
no_Reason_df_eden_indigo_week_20=Reason_df_eden_indigo_week_20[
    (Reason_df_eden_indigo_week_20['combined_reason']=='')
]
#df_eden_indigo_week_36=df_eden_indigo_week_36[~df_eden_indigo_week_36['participant_id'].isin(df_withdrawal['participant_id'])]

df_eden_indigo_week_20_fellow_up=df_eden_indigo_week_20[~df_eden_indigo_week_20['participant_id'].isin(df_withdrawal['participant_id'])]
#df_eden_indigo_week_20=df_eden_indigo_week_20[~df_eden_indigo_week_20['participant_id'].isin(df_eden_indigo_deveries['participant_id'])]
df_eden_indigo_week_20 = df_eden_indigo_week_20.drop_duplicates('participant_id')

# Eden Indigo week 28
df_eden_indigo_week_28 = pd.concat([df_eden_week_28, df_merged_week_28], ignore_index=True)
df_eden_indigo_week_28 = df_eden_indigo_week_28.drop_duplicates('participant_id')

Reason_df_eden_indigo_week_28=df_withdrawal[df_withdrawal['participant_id'].isin(df_eden_indigo_week_28['participant_id'])]
Reason_df_eden_indigo_week_28.to_csv('Reason_df_eden_indigo_week_28.csv',index=False)

Moved_away_Reason_df_eden_indigo_week_28=Reason_df_eden_indigo_week_28[
    (Reason_df_eden_indigo_week_28['combined_reason']!='')
]
no_Reason_df_eden_indigo_week_28=Reason_df_eden_indigo_week_28[
    (Reason_df_eden_indigo_week_28['combined_reason']=='')
]
df_eden_indigo_week_28_follow_up=df_eden_indigo_week_28[~df_eden_indigo_week_28['participant_id'].isin(df_withdrawal['participant_id'])]
#df_eden_indigo_week_28=df_eden_indigo_week_28[~df_eden_indigo_week_28['participant_id'].isin(df_eden_indigo_deveries['participant_id'])]
df_eden_indigo_week_28 = df_eden_indigo_week_28.drop_duplicates('participant_id')

# Eden Indigo week 36
df_eden_indigo_week_36 = pd.concat([df_eden_week_36, df_merged_week_36], ignore_index=True)
df_eden_indigo_week_36 = df_eden_indigo_week_36.drop_duplicates('participant_id')

Reason_df_eden_indigo_week_36=df_withdrawal[df_withdrawal['participant_id'].isin(df_eden_indigo_week_36 ['participant_id'])]
Reason_df_eden_indigo_week_36.to_csv('Reason_df_eden_indigo_week_36.csv',index=False)

Moved_away_Reason_df_eden_indigo_week_36=Reason_df_eden_indigo_week_36[
    (Reason_df_eden_indigo_week_36['combined_reason']!='')
]
no_Reason_df_eden_indigo_week_36=Reason_df_eden_indigo_week_36[
    (Reason_df_eden_indigo_week_36['combined_reason']=='')
]
df_eden_indigo_week_36_follow_up=df_eden_indigo_week_36[~df_eden_indigo_week_36['participant_id'].isin(df_withdrawal['participant_id'])]
#df_eden_indigo_week_36=df_eden_indigo_week_36[~df_eden_indigo_week_36['participant_id'].isin(df_eden_indigo_deveries['participant_id'])]
df_eden_indigo_week_36 = df_eden_indigo_week_36.drop_duplicates('participant_id')

# Eden Indigo deliveries
df_eden_indigo_deveries = pd.concat([df_indigo_deliveries, df_eden_deliveries], ignore_index=True)
df_eden_indigo_deveries = df_eden_indigo_deveries.drop_duplicates('participant_id')
follow_up_eden_indigo_deveries=df_eden_indigo_deveries[~df_eden_indigo_deveries['participant_id'].isin(df_withdrawal['participant_id'])]
df_withdrawal_eden_indigo_deveries=df_withdrawal[df_withdrawal['participant_id'].isin(df_eden_indigo_deveries['participant_id'])]
# Cord and placenta collection
df_eden_indigo_cord_collection = pd.concat([df_eden_cord_collection, df_indigo_cord_collection], ignore_index=True)
df_eden_indigo_cord_collection = df_eden_indigo_cord_collection.drop_duplicates('participant_id')
Reason_df_eden_indigo_cord_collection=df_eden_indigo_cord_collection[~df_eden_indigo_cord_collection['participant_id'].isin(df_withdrawal['participant_id'])]
df_withdrawal_df_eden_indigo_cord_collection=df_withdrawal[df_withdrawal['participant_id'].isin(df_eden_indigo_cord_collection['participant_id'])]
# Eden Indigo placenta collection
df_eden_indigo_placenta_collection = pd.concat([df_eden_placenta_collection, df_indigo_placenta_collection], ignore_index=True)
df_eden_indigo_placenta_collection = df_eden_indigo_placenta_collection.drop_duplicates('participant_id')
Reason_df_eden_indigo_placenta_collection=df_eden_indigo_placenta_collection[~df_eden_indigo_placenta_collection['participant_id'].isin(df_withdrawal['participant_id'])]
df_withdrawal_df_eden_indigo_placenta_collection=df_withdrawal[df_withdrawal['participant_id'].isin(df_eden_indigo_placenta_collection['participant_id'])]
# Seasonal blood collection
df_seasonal_blood_collection = df_seasonal_blood_collection[
    (df_seasonal_blood_collection['sbc_date'] != '')
]

# Blood sample
df_blood = df_sample_collection[['participant_id', 'matbld_visitdate_q1_e327e1', 'matbld_4mlcollected_q2', 'bloodcycle', 'maternal_blood_sample_collection_complete']]
df_blood = df_blood[
    (df_blood['maternal_blood_sample_collection_complete'] == '2')
]
df_blood = pd.merge(df_HCG_positive, df_blood, on='participant_id', how='inner')
df_blood = df_blood.sort_values(by=['participant_id', 'matbld_visitdate_q1_e327e1'])
df_blood = df_blood.drop_duplicates(subset='participant_id', keep='last')
#df_blood=df_blood[~df_blood['participant_id'].isin(df_withdrawal['participant_id'])]
# Stool sample
df_stool = df_sample_collection[['participant_id', 'mstool_vdate', 'mstool_time', 'stolcycle', 'preganancy_stool_collection_complete']]
df_stool = df_stool[
    (df_stool['preganancy_stool_collection_complete'] == '2')
]
df_stool = pd.merge(df_HCG_positive, df_stool, on='participant_id', how='inner')
#df_stool=df_stool[~df_stool['participant_id'].isin(df_withdrawal['participant_id'])]
df_stool = df_stool.sort_values(by=['participant_id', 'mstool_vdate'])
df_stool = df_stool.drop_duplicates(subset='participant_id', keep='last')

# Urine sample
df_urine = df_sample_collection[['participant_id', 'urine_date', 'urinecollected', 'uricycle', 'preganancy_urine_collection_complete']]
df_urine = df_urine[
    (df_urine['preganancy_urine_collection_complete'] == '2')
]
#df_urine=df_urine[~df_urine['participant_id'].isin(df_withdrawal['participant_id'])]
df_urine = pd.merge(df_HCG_positive, df_urine, on='participant_id', how='inner')
df_urine = df_urine.sort_values(by=['participant_id', 'urine_date'])
df_urine = df_urine.drop_duplicates(subset='participant_id', keep='last')

# Print the number of participant IDs for each dataframe
print("#sensitized:", df_enumeration_and_sensitisation.shape[0])
print("Interested:", df_interested.shape[0])
print("Not Interested:", df_not_interested.shape[0])
print("Undecided:", df_undecided.shape[0])
print("Others:", df_other.shape[0])
print('')
print('')
print("screen:",df_screen.shape[0])
print("Consented:", df_consented_v4.shape[0])
print("Declined Consent:", df_decline_consent_v4.shape[0])
print('')
print('')
print("Temporal exclusion:",data_lmp_temp_exclusion.shape[0])
print("cycle 35 LMP:",df_lmp.shape[0])
#print("Eden Withdrawal:", df_withdrawal.shape[0])
print('')
print('')
print("HCG Positive:", df_HCG_positive.shape[0])
print("Blood Sample:", df_blood.shape[0])
print("Urine Sample:", df_urine.shape[0])
print("Stool Sample:", df_stool.shape[0])


#booking
print("Total Indigo Booking:", df_eden_indigo_booking.shape[0])
print("withdrawal up Booking scann:", Reason_fellow_up_booking_scan.shape[0])
#print("fellow up booking scann:", fellow_up_booking_scan.shape[0])
print("fellow up booking scann:", fellow_up_booking_scan_fellow_up1.shape[0])

print('')
print('')
#week 20
print("Total Eden Indigo Week 20:", df_eden_indigo_week_20.shape[0])
print("Withdrawal with Eden Indigo Week 20:", Reason_df_eden_indigo_week_20.shape[0])
print("fellow Eden Indigo Week 20:", df_eden_indigo_week_20_fellow_up.shape[0])
print('')
print('')
#week 28
print("Total Eden Indigo Week 28:", df_eden_indigo_week_28.shape[0])
print("Withdrawal Eden Indigo Week 28:", Reason_df_eden_indigo_week_28.shape[0])
print("fellow up Eden Indigo Week 28:", df_eden_indigo_week_28_follow_up.shape[0])

print('')
print('')
#week 36
print("Total Eden Indigo Week 36:", df_eden_indigo_week_36.shape[0])
print("Withdrawal Eden Indigo Week 36:", Reason_df_eden_indigo_week_36.shape[0])
print("follow up Eden Indigo Week 36:", df_eden_indigo_week_36_follow_up.shape[0])

print('')
print('')
print("Total Indigo Deliveries:", df_eden_indigo_deveries.shape[0])
print("Withdrawal Indigo Deliveries:", df_withdrawal_eden_indigo_deveries.shape[0])
print("fellow up Indigo Deliveries:", follow_up_eden_indigo_deveries.shape[0])
print('')
print('')
#cord collection 
print("Total Indigo Cord Collection:", df_eden_indigo_cord_collection.shape[0])
print("withdrawal  Indigo Cord Collection:", df_withdrawal_df_eden_indigo_cord_collection.shape[0])
print("fellow up Eden Indigo cordblood:", Reason_df_eden_indigo_cord_collection.shape[0])

print('')
print('')
#pacental collection
print("Total Eden Indigo Placenta Collection:", df_eden_indigo_placenta_collection.shape[0])
print("withdrawal Indigo Placenta Collection:",df_withdrawal_df_eden_indigo_placenta_collection.shape[0])
print("fellow up Indigo Placenta Collection:", Reason_df_eden_indigo_placenta_collection.shape[0])
print("Seasonal Blood Collection:", df_seasonal_blood_collection.shape[0])

print('')
print('')
# reason for withdrawal:

print("booking reason withdrawal moved away :", Moved_away_Reason_fellow_up_booking_scan.shape[0])
print("booking reason withdrawal no reason given :", no_Reason_Reason_fellow_up_booking_scan.shape[0])

print('')
print('')
print("week 20 reason withdrawal moved away :", Moved_away_Reason_df_eden_indigo_week_20.shape[0])
print("week 20 reason withdrawal no reason given :", no_Reason_df_eden_indigo_week_20.shape[0])
print('')
print('')

print("week 28 reason withdrawal moved away :", Moved_away_Reason_df_eden_indigo_week_28.shape[0])
print("week 28 reason withdrawal no reason given :", no_Reason_df_eden_indigo_week_28.shape[0])
print('')
print('')
print("week 36 reason withdrawal moved away :", Moved_away_Reason_df_eden_indigo_week_36.shape[0])
print("week 36 reason withdrawal no reason given :", no_Reason_df_eden_indigo_week_36.shape[0])

#sensitized: 4748
Interested: 2877
Not Interested: 331
Undecided: 549
Others: 991


screen: 2497
Consented: 1411
Declined Consent: 666


Temporal exclusion: 492
cycle 35 LMP: 748


HCG Positive: 532
Blood Sample: 512
Urine Sample: 520
Stool Sample: 501
Total Indigo Booking: 548
withdrawal up Booking scann: 160
fellow up booking scann: 367


Total Eden Indigo Week 20: 380
Withdrawal with Eden Indigo Week 20: 67
fellow Eden Indigo Week 20: 313


Total Eden Indigo Week 28: 361
Withdrawal Eden Indigo Week 28: 48
fellow up Eden Indigo Week 28: 313


Total Eden Indigo Week 36: 327
Withdrawal Eden Indigo Week 36: 37
follow up Eden Indigo Week 36: 290


Total Indigo Deliveries: 326
Withdrawal Indigo Deliveries: 39
fellow up Indigo Deliveries: 287


Total Indigo Cord Collection: 284
withdrawal  Indigo Cord Collection: 26
fellow up Eden Indigo cordblood: 258


Total Eden Indigo Placenta Collection: 277
withdrawal Indigo Placenta Collection: 25
fellow up Indigo Placenta Collection: 252
Seasonal Blood Collection: 143


booking reason withdrawal moved away : 117
booking reason withdrawal no reason given : 43


week 20 reason withdrawal moved away : 49
week 20 reason withdrawal no reason given : 18


week 28 reason withdrawal moved away : 43
week 28 reason withdrawal no reason given : 5


week 36 reason withdrawal moved away : 35
week 36 reason withdrawal no reason given : 2

C:\Users\abliebah\AppData\Local\Temp\ipykernel_21144\1350379400.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fellow_up_booking_scan_fellow_up1['Are Elegible']='Accept consent'

In [25]:
df_eden_indigo_deveries1=pd.merge(df_eden_indigo_cord_collection,df_eden_indigo_placenta_collection,on='participant_id',how='left')
#df_eden_indigo_deveries2=pd.merge(df_eden_indigo_deveries1,df_eden_indigo_cord_collection,on='participant_id',how='left')
df_eden_indigo_deveries1

,participant_id,cordcollection_form_date_q15_x,cod_vailable,con_participantid_q1_x,date_form_completed_15_x,cbc_cord_blood_q3,cordcollection_form_date_q15_y,placenta_available,con_participantid_q1_y,date_form_completed_15_y
0,EDN0005-K,2022-12-13,1,NaN,NaN,NaN,2022-12-13,1,NaN,NaN
1,EDN0011-H,2024-08-05,1,NaN,NaN,NaN,2024-08-05,1,NaN,NaN
2,EDN0017-E,2022-12-19,1,NaN,NaN,NaN,2022-12-19,1,NaN,NaN
3,EDN0023-C,2023-07-15,1,NaN,NaN,NaN,2023-07-15,1,NaN,NaN
4,EDN0034-D,2023-11-03,1,NaN,NaN,NaN,2023-11-03,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
279,EDN1227-B,NaN,NaN,IN-M-496D,2025-03-19,1,NaN,NaN,NaN,NaN
280,EDN0004-F,NaN,NaN,IN-M-519J,2025-02-07,1,NaN,NaN,NaN,NaN
281,EDN0859-J,NaN,NaN,IN-M-554A,2025-04-20,1,2025-04-20,1,NaN,NaN
282,EDN2088-T,NaN,NaN,IN-M-565F,2025-04-21,1,NaN,NaN,NaN,NaN
283,EDN2793-T,NaN,NaN,IN-M-647G,2025-03-28,1,NaN,NaN,NaN,NaN

In [ ]:
df_merged_week_20

In [27]:
fellow_up_booking_scan
df_recruit=df.export_records(forms=['recruitment'])
df_recruit=pd.DataFrame(df_recruit)
df_recruit=df_recruit[['participant_id','rdob']]
df_recruit=df_recruit[
 (df_recruit['rdob']!='')
]
fellow_up_booking_scan1=pd.merge(df_eden_indigo_booking,df_recruit,on='participant_id',how='left')
fellow_up_booking_scan1.drop_duplicates('participant_id')

fellow_up_booking_scan2=pd.merge(fellow_up_booking_scan1,df_eden_indigo_deveries,on='participant_id',how='left')
fellow_up_booking_scan2.drop_duplicates('participant_id')

fellow_up_booking_scan3=pd.merge(fellow_up_booking_scan2,df_eden_indigo_placenta_collection,on='participant_id',how='left')
fellow_up_booking_scan4=pd.merge(fellow_up_booking_scan3,df_eden_indigo_id,on='participant_id',how='left')

C:\Users\abliebah\AppData\Local\Temp\ipykernel_21144\1260033598.py:15: FutureWarning: Passing 'suffixes' which cause duplicate columns {'con_participantid_q1_x'} in the result is deprecated and will raise a MergeError in a future version.
  fellow_up_booking_scan4=pd.merge(fellow_up_booking_scan3,df_eden_indigo_id,on='participant_id',how='left')

In [46]:
booking_withdr=df.export_records(forms=['withdrawal'])
booking_withdr=pd.DataFrame(booking_withdr)

booking_withdr=booking_withdr[['participant_id','wd_vdadte_q1','wd_reason','b_give_medical_reason']]
booking_withdr=booking_withdr[
    (booking_withdr['wd_vdadte_q1']!='')
]

fellow_up_booking_scan5=pd.merge(fellow_up_booking_scan4,booking_withdr,on='participant_id',how='left').drop_duplicates('participant_id')
df_eden_indigo_booking.to_csv('df_eden_indigo_booking.csv',index=False)
fellow_up_booking_scan5.head(5)
fellow_up_booking_scan5

,participant_id,conception_date,comments_scan_x,con_participantid_q1_x,ultsc_date_x,ga_weeks_x,ga_days_x,rdob,con_participantid_q1_y,ultsc_date_y,...,con_participantid_q1_x,date_form_completed_15,con_participantid_q1_y,ultsc_date,ga_weeks,ga_days,comments_scan,wd_vdadte_q1,wd_reason,b_give_medical_reason
0,EDN0004-F,2024-05-03,Oblique presentation,NaN,NaN,NaN,NaN,1985-12-14,IN-M-519J,2024-08-28,...,NaN,NaN,IN-M-519J,2024-08-28,16,5,Oblique presentation,NaN,NaN,NaN
2,EDN0005-K,2022-03-01,The above features were NOT measured by Doctor...,NaN,NaN,NaN,NaN,1999-10-14,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,EDN0009-C,2022-11-13,Breech presentation with fetal heart rate of ...,NaN,NaN,NaN,NaN,2001-10-05,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EDN0011-H,2023-10-21,Scan results can be obtained from the INDIGO d...,NaN,NaN,NaN,NaN,1987-05-16,IN-M-226E,2024-02-13,...,NaN,NaN,IN-M-226E,2024-02-13,16,3,,NaN,NaN,NaN
6,EDN0017-E,2022-03-20,,NaN,NaN,NaN,NaN,1992-02-11,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,EDN1939-J,NaN,No pregnancy detected on ultrasound and HCG is...,IN-M-445G,2024-07-11,,,1998-11-05,NaN,NaN,...,NaN,NaN,IN-M-445G,2024-07-11,,,No pregnancy detected on ultrasound and HCG is...,NaN,NaN,NaN
611,EDN0366-B,NaN,Came for reschedule visit today but no pregnan...,IN-M-470A,2024-11-26,,,1988-06-10,NaN,NaN,...,NaN,NaN,IN-M-470A,2024-11-26,,,Came for reschedule visit today but no pregnan...,2024-11-26,3,
612,EDN0837-E,NaN,No pregnancy detected \r\nHCG Negative,IN-M-544H,2024-09-04,,,1992-05-17,NaN,NaN,...,NaN,NaN,IN-M-544H,2024-09-04,,,No pregnancy detected \r\nHCG Negative,NaN,NaN,NaN
614,EDN1532-E,NaN,only gestational sac seen and measured. appoi...,IN-M-643G,2025-01-27,,,2002-08-01,NaN,NaN,...,NaN,NaN,IN-M-643G,2025-01-27,,,only gestational sac seen and measured. appoi...,2025-01-27,3,
615,EDN0623-A,NaN,only gestation sac seen and measured that read...,IN-M-682A,2025-03-10,,,1987-05-05,NaN,NaN,...,NaN,NaN,IN-M-682A,2025-03-10,,,only gestation sac seen and measured that read...,2025-03-10,5,miscarriage

In [29]:
df_outstanding=pd.merge(df_HCG_positive,df_eden_indigo_deveries,on='participant_id',how='outer').sort_values('pt_testdate_q1')
df_outstanding1=pd.merge(df_outstanding,df_withdrawal,on='participant_id',how='left')
df_outstanding1

,participant_id,prg_cycle,pt_testdate_q1,pt_pregnancy_positive_q3,con_participantid_q1,ultsc_date,ga_weeks,ga_days,comments_scan,del_ddate_q7,del_sex_q10,del_outcome_q9,delivery_complete,combined_reason,b_give_medical_reason
0,EDN0264-A,1,2022-05-10,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moved away,Off-Peak Season Conception
1,EDN0165-J,3,2022-05-10,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moved away,Had an abortion
2,EDN0310-C,4,2022-05-11,1,NaN,NaN,NaN,NaN,NaN,2022-12-29,2,NaN,2,NaN,NaN
3,EDN0242-K,5,2022-05-19,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moved away,ineligible
4,EDN0275-B,1,2022-05-19,1,NaN,NaN,NaN,NaN,NaN,2022-12-02,1,NaN,2,Moved away,Conceived outside of conception period.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,EDN0538-G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-02-21,1,NaN,2,NaN,NaN
556,EDN0698-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-29,,NaN,2,Moved away,Twin gestation
557,EDN0708-J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-08-28,2,NaN,2,Moved away,Conceived outside of conception period.
558,EDN0790-G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-12,,NaN,2,Moved away,Twin pregnancy
559,EDN0818-G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-14,2,NaN,2,Moved away,Conceived outside of conception period.

In [30]:
missing_plancet=pd.merge(df_eden_indigo_deveries,df_eden_indigo_placenta_collection,on='participant_id',how='left')
sub=df_eden_indigo_deveries[~df_eden_indigo_deveries['participant_id'].isin(df_eden_indigo_placenta_collection['participant_id'])]
sub1=sub[~sub['participant_id'].isin(df_withdrawal['participant_id'])]
sub2=sub1[~sub1['participant_id'].isin(df_eden_no_placenta_collection['participant_id'])].sort_values('del_ddate_q7',ascending=False)

sub2

,con_participantid_q1,participant_id,ultsc_date,ga_weeks,ga_days,comments_scan,del_ddate_q7,del_sex_q10,del_outcome_q9,delivery_complete
202,IN-M-565F,EDN2088-T,2024-09-19,9,5,,2025-04-21,1,1,NaN
213,IN-M-647G,EDN2793-T,2024-11-06,18,5,,2025-03-28,2,1,NaN
183,IN-M-505A,EDN2785-J,2024-08-21,7,5,,2025-03-19,2,1,NaN
180,IN-M-496D,EDN1227-B,2024-08-13,9,1,,2025-03-08,2,1,NaN
159,IN-M-451B,EDN1709-C,2024-07-17,8,0,Transverse presentation,2025-02-16,2,1,NaN
186,IN-M-519J,EDN0004-F,2024-08-28,16,5,Oblique presentation,2025-02-07,2,1,NaN
147,IN-M-427G,EDN0529-F,2024-07-03,7,4,,2025-02-06,1,1,NaN
169,IN-M-471A,EDN1605-K,2024-07-24,13,1,,2025-02-06,1,1,NaN
158,IN-M-449F,EDN0020-H,2024-07-17,14,1,Transverse presentation,2025-01-21,1,1,NaN
120,IN-M-364B,EDN0426-C,2024-06-26,12,0,Pregnancy too young that only gestational sac ...,2025-01-17,2,1,NaN
459,NaN,EDN1411-K,NaN,NaN,NaN,NaN,2024-12-30,1,NaN,2
179,IN-M-495J,EDN1802-C,2024-08-08,17,5,,2024-12-27,2,1,NaN
84,IN-M-245J,EDN1429-D,2024-02-22,11,1,,2024-08-30,1,1,NaN
64,IN-M-166D,EDN0931-J,2023-11-08,8,4,,2024-06-11,1,1,NaN
55,IN-M-140D,EDN0862-H,2023-10-18,18,6,,2024-03-15,2,1,NaN
60,IN-M-151B,EDN0649-E,2023-10-18,18,6,,2024-02-11,2,1,NaN
20,IN-M-031D,EDN0964-B,2023-04-27,13,1,,2023-11-01,1,1,NaN
423,NaN,EDN1004-D,NaN,NaN,NaN,NaN,2023-10-14,1,NaN,2
309,NaN,EDN0534-B,NaN,NaN,NaN,NaN,2023-10-07,1,NaN,2
264,NaN,EDN0285-C,NaN,NaN,NaN,NaN,2022-12-30,2,NaN,2
267,NaN,EDN0307-C,NaN,NaN,NaN,NaN,2022-12-30,1,NaN,2

In [31]:
sample_id=pd.read_csv('LPS_funded_EDEN_IDs_for_maternal_genotyping.csv')
sample_id=pd.DataFrame(sample_id)
sample_id_m=pd.merge(sample_id,df_blood,on='participant_id',how='left')
sample_id_m.to_csv('sample_id_m.csv',index=False)

In [32]:
df_blood

,participant_id,prg_cycle,pt_testdate_q1,pt_pregnancy_positive_q3,matbld_visitdate_q1_e327e1,matbld_4mlcollected_q2,bloodcycle,maternal_blood_sample_collection_complete
0,EDN0001-D,36,2024-11-13,1,2024-11-14,1,36,2
5,EDN0004-F,30,2024-06-12,1,2024-06-13,1,30,2
6,EDN0005-K,1,2022-06-14,1,2022-05-06,1,2,2
14,EDN0011-H,26,2024-02-02,1,2024-02-01,1,26,2
15,EDN0017-E,8,2022-06-28,1,2022-06-28,1,4,2
...,...,...,...,...,...,...,...,...
1025,EDN2824-F,37,2024-12-03,1,2024-12-04,1,37,2
1026,EDN2825-R,35,2024-10-01,1,2024-10-02,1,35,2
1027,EDN2829-V,37,2024-12-14,1,2024-12-15,1,37,2
1028,EDN2855-F,36,2024-10-25,1,2024-10-28,1,36,2
1029,EDN2864-L,36,2024-11-07,1,2024-11-12,1,36,2

In [33]:
df_processing_form=df.export_records(forms=['cord_placenta_processing'])
df_processing_form=pd.DataFrame(df_processing_form)
df_processing_form=df_processing_form[
    (df_processing_form['cord_placenta_processing_complete']=='2')|
    (df_processing_form['cord_placenta_processing_complete']=='1')
]

In [34]:
march=pd.merge(df_eden_indigo_placenta_collection,df_processing_form,on='participant_id',how='left')
march1=march[
    (march['cpp_visit_date'].isnull())
]
march1

,participant_id,cordcollection_form_date_q15,placenta_available,con_participantid_q1,date_form_completed_15,redcap_event_name,redcap_repeat_instrument,redcap_repeat_instance,cpp_placenta,cpp_visit_date,...,cpp_processedby,cpp_cordblood,cpp_cordprocessed,cpp_edta_aliquot,cpp_lithhep_aliquot,cpp_edtapellets,cpp_cordstoretime,cpp_comments,cpp_cordprocessby,cord_placenta_processing_complete
25,EDN0197-B,2025-03-23,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,EDN0206-C,2024-10-25,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,EDN0263-D,2024-09-15,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,EDN0275-B,2022-12-02,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,EDN0313-B,2023-11-05,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,EDN0336-K,2025-04-10,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,EDN0355-C,2023-06-13,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,EDN0460-C,2024-04-07,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,EDN0505-H,2024-07-20,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,EDN0541-B,2023-02-23,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,EDN0551-H,2024-02-22,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,EDN0574-D,2025-03-19,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,EDN0629-G,2022-11-14,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,EDN0688-E,2023-10-07,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,EDN0701-G,2023-06-28,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,EDN0759-K,2023-10-05,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,EDN0777-J,2025-03-27,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,EDN0888-B,2023-04-19,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,EDN0904-A,2023-09-25,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,EDN0932-G,2025-04-08,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,EDN0937-B,2024-06-25,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,EDN0972-F,2023-06-26,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,EDN1003-C,2023-10-06,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,EDN1007-G,2023-11-30,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,EDN1081-F,2024-04-01,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,EDN1089-N,2024-09-18,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,EDN1095-T,2024-10-24,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,EDN1216-P,2025-03-29,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,EDN1243-R,2025-04-10,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,EDN1340-O,2025-01-19,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,EDN1413-M,2024-10-25,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,EDN1433-H,2025-03-11,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,EDN1646-K,2024-07-24,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,EDN1707-G,2024-12-09,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,EDN1757-H,2025-04-05,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,EDN1818-D,2025-04-22,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,EDN1972-K,2025-04-10,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,EDN2082-G,2025-03-25,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,EDN2090-S,2025-04-02,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,EDN2120-Z,2024-11-24,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,EDN2160-N,2025-01-30,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,EDN2392-A,2025-02-26,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,EDN2614-B,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,EDN2672-D,2025-03-30,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN